# Scenario version: 0.2.1
# Generated by Mission Generator v2; RNG seed: baltic-setup-v1
from math import *


def ScenarioInfo():
    d = dict()
    d['name'] = "Baltic Operational Area - Technical Validation Only"
    d['description'] = """Synthetic geography and database validation fixture. Not the first campaign mission or a prediction of conflict.

Mission archetype: Convoy Escort. This scenario was generated from campaign turn 0 with deterministic seed baltic-setup-v1."""
    d['author'] = 'Mission Generator v2'
    d['playableSides'] = "NATO"
    d['thumb'] = 'ships3.png'
    d['date'] = "June 2026"
    d['unitCount'] = 3
    d['scenarioId'] = "baltic_setup_validation"
    return d


def CreateScenario(SM):
    SM.SetScenarioInfo(ScenarioInfo())

    SM.CreateAlliance(1, "NATO")
    SM.AddAllianceCountry(1, "Germany")
    SM.AddAllianceCountry(1, "UK")
    SM.SetAlliancePlayable(1, 1)

    SM.CreateAlliance(2, "Russia")
    SM.AddAllianceCountry(2, "Russia")
    SM.SetAlliancePlayable(2, 0)

    SM.SetAllianceRelationship(1, 2, 'Hostile')
    SM.SetUserAlliance(1)
    SM.SetDateTime(2026, 6, 15, 10, 0, 0)
    SM.SetSeaState(3)
    SM.SetSVP("0.000000,1515.000000,200.000000,1500.000000,300.000000,1510.000000,500.000000,1520.000000,5000.000000,1600.000000")

    SM.SetSimpleBriefing(1, """<color=#00a8ff>SITUATION</color>

Synthetic geography and database validation fixture. Not the first campaign mission or a prediction of conflict.

<color=#00a8ff>MISSION</color>

Preserve at least 1 of: TEST NATO Logistics. Also Neutralize at least 1 of: TEST Russian Corvette.

<color=#00a8ff>EXECUTION</color>

Validate escort and logistics placement.

<color=#00a8ff>ROE</color>

Technical fixture only; hostile alliance settings are not a campaign starting policy.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 1.068.""")
    SM.SetSimpleBriefing(2, """<color=#00a8ff>SITUATION</color>

Synthetic geography and database validation fixture. Not the first campaign mission or a prediction of conflict.

<color=#00a8ff>MISSION</color>

Neutralize at least 1 of: TEST NATO Logistics.

<color=#00a8ff>EXECUTION</color>

Validate a Russian database platform and opposing objective.

<color=#00a8ff>ROE</color>

Technical fixture only; hostile alliance settings are not a campaign starting policy.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 1.068.""")

    ##############################
    ### Alliance 1 - BLUE
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "Sachsen FFGHM"
    unit.unitName = "TEST NATO Escort"
    unit.SetPosition(56.100000, 20.100000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 20.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RIM-66M", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-162B", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RIM-116B RAM", 21)
    SM.SetUnitLauncherItem(unit.unitName, 3, "RIM-116B RAM", 21)
    SM.SetUnitLauncherItem(unit.unitName, 4, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 6, "76mm HE-MOM", 80)
    SM.SetUnitLauncherItem(unit.unitName, 7, "27mm DM10 FAPDS", 90)
    SM.SetUnitLauncherItem(unit.unitName, 8, "27mm DM10 FAPDS", 90)
    SM.SetUnitLauncherItem(unit.unitName, 9, "MU-90", 3)
    SM.SetUnitLauncherItem(unit.unitName, 10, "MU-90", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 23700)
    SM.AddToUnitMagazine(unit.unitName, "Mk-46 Mod5", 29)
    SM.AddToUnitMagazine(unit.unitName, "Sea Skua", 16)
    SM.AddToUnitMagazine(unit.unitName, "RIM-162B", 32)
    SM.AddToUnitMagazine(unit.unitName, "RIM-66M", 24)
    SM.AddToUnitMagazine(unit.unitName, "RIM-116B RAM", 84)
    SM.AddToUnitMagazine(unit.unitName, "76mm HE-MOM", 240)
    SM.AddToUnitMagazine(unit.unitName, "27mm DM10 FAPDS", 1000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(56.800000, 20.150000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(57.200000, 20.150000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Fort Victoria AOR"
    unit.unitName = "TEST NATO Logistics"
    unit.SetPosition(56.050000, 20.000000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "20mm Mark 149-4", 141)
    SM.SetUnitLauncherItem(unit.unitName, 1, "20mm Mark 149-4", 141)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    SM.AddToUnitMagazine(unit.unitName, "20mm Mark 149-4", 970)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.800000, 20.150000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(57.200000, 20.150000, 0.000000, 16.000000)

    ##############################
    ### Alliance 2 - RED
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "Pr 20380 Steregushchiy"
    unit.unitName = "TEST Russian Corvette"
    unit.SetPosition(57.600000, 20.300000, 0.000000)
    unit.heading = 135.000000
    unit.speed = 20.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "100mm OF-58 FRAG", 46)
    SM.SetUnitLauncherItem(unit.unitName, 1, "12.7mm B-32 APi", 17)
    SM.SetUnitLauncherItem(unit.unitName, 2, "12.7mm B-32 APi", 17)
    SM.SetUnitLauncherItem(unit.unitName, 3, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 4, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 5, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 6, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Kh-35", 8)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    SM.AddToUnitMagazine(unit.unitName, "100mm OF-58 FRAG", 350)
    SM.AddToUnitMagazine(unit.unitName, "12.7mm B-32 APi", 680)
    SM.AddToUnitMagazine(unit.unitName, "30mm OF-84 HE-FRAG AK-630M", 472)
    SM.AddToUnitMagazine(unit.unitName, "9M311 Kashtan", 48)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(57.400000, 20.300000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(57.000000, 20.300000, 0.000000, 16.000000)

    ##############################
    ### Goals
    ##############################

    goal_temp = SM.ProtectGoal('')
    goal_temp.AddTarget("TEST NATO Logistics")
    goal_temp.SetQuantity(1)
    blue_0 = goal_temp
    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("TEST Russian Corvette")
    goal_temp.SetQuantity(1)
    blue_1 = goal_temp
    goal_temp = SM.CompoundGoal(0)
    goal_temp.AddGoal(blue_0)
    goal_temp.AddGoal(blue_1)
    SM.SetAllianceGoal(1, goal_temp)

    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("TEST NATO Logistics")
    goal_temp.SetQuantity(1)
    red_goal = goal_temp
    SM.SetAllianceGoal(2, red_goal)

    SM.SetAllianceROEByType(1, 2, 2, 2, 2)
    SM.SetAllianceROEByType(2, 2, 2, 2, 2)
