# Scenario version: 0.2.1
# Generated by Mission Generator v2; RNG seed: 20260822
from math import *


def ScenarioInfo():
    d = dict()
    d['name'] = "Operation Resolute Passage — Campaign Generated"
    d['description'] = """The surviving coalition logistics force must make a westbound passage through Hormuz before forward stocks in Bahrain fall below contingency levels. Iran's surviving coastal kill chain and fast attack craft will attempt to break the convoy inside the Strait.

Mission archetype: Convoy Escort. This scenario was generated from campaign turn 5 with deterministic seed 20260822."""
    d['author'] = 'Mission Generator v2'
    d['playableSides'] = "Blue"
    d['thumb'] = 'ships3.png'
    d['date'] = "May 2026"
    d['unitCount'] = 23
    d['scenarioId'] = "resolute_passage_generated_001"
    return d


def CreateScenario(SM):
    SM.SetScenarioInfo(ScenarioInfo())

    SM.CreateAlliance(1, 'Blue')
    SM.AddAllianceCountry(1, 'Blue')
    SM.AddAllianceCountry(1, 'USA')
    SM.AddAllianceCountry(1, 'UK')
    SM.SetAlliancePlayable(1, 1)

    SM.CreateAlliance(2, 'Red')
    SM.AddAllianceCountry(2, 'Red')
    SM.AddAllianceCountry(2, 'Iran')
    SM.SetAlliancePlayable(2, 0)

    SM.SetAllianceRelationship(1, 2, 'Hostile')
    SM.SetUserAlliance(1)
    SM.SetDateTime(2026, 5, 22, 13, 53, 0)
    SM.SetSeaState(4)
    SM.SetSVP("0.000000,1515.000000,200.000000,1500.000000,300.000000,1510.000000,500.000000,1520.000000,5000.000000,1600.000000")

    SM.SetSimpleBriefing(1, """<color=#00a8ff>SITUATION</color>

The surviving coalition logistics force must make a westbound passage through Hormuz before forward stocks in Bahrain fall below contingency levels. Iran's surviving coastal kill chain and fast attack craft will attempt to break the convoy inside the Strait.

<color=#00a8ff>MISSION</color>

Preserve at least 2 of: RFA Fort Victoria, USNS Amelia Earhart, USNS John Ericsson. Also Neutralize at least 2 of: Bastion 1, Bastion 2, Falakhon, Khanjar.

<color=#00a8ff>EXECUTION</color>

Keep the logistics ships behind the defensive screen, classify contacts at range, and open only the corridor needed for the westbound passage.

<color=#00a8ff>ROE</color>

BLUE shore attack is limited to designated coastal kill-chain nodes. Neither side is authorized to expand the operation beyond the Hormuz corridor.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 1.089.""")
    SM.SetSimpleBriefing(2, """<color=#00a8ff>SITUATION</color>

The surviving coalition logistics force must make a westbound passage through Hormuz before forward stocks in Bahrain fall below contingency levels. Iran's surviving coastal kill chain and fast attack craft will attempt to break the convoy inside the Strait.

<color=#00a8ff>MISSION</color>

Neutralize at least 2 of: RFA Fort Victoria, USNS Amelia Earhart, USNS John Ericsson.

<color=#00a8ff>EXECUTION</color>

Use the coastal sensor and missile network to cue the surviving fast attack craft against the coalition logistics backbone.

<color=#00a8ff>ROE</color>

BLUE shore attack is limited to designated coastal kill-chain nodes. Neither side is authorized to expand the operation beyond the Hormuz corridor.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 1.089.""")

    ##############################
    ### Alliance 1 - BLUE
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "P-8 MPA"
    unit.unitName = "Broadarrow"
    unit.SetPosition(25.247606, 57.377629, 8000.000000)
    unit.heading = 285.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.640000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(26.100000, 57.500000, 7600.000000, 280.000000)
    UI.add_waypoint_advanced(25.950000, 56.950000, 7600.000000, 280.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Type 45 DDG"
    unit.unitName = "HMS Diamond"
    unit.SetPosition(25.380000, 58.080000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "ASTER 30", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "ASTER 15", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "20mm mark 244-0 ELC", 78)
    SM.SetUnitLauncherItem(unit.unitName, 3, "20mm mark 244-0 ELC", 78)
    SM.SetUnitLauncherItem(unit.unitName, 4, "114mm N4A1 HE", 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.780000)
    SM.AddToUnitMagazine(unit.unitName, "ASTER 15", 8)
    SM.AddToUnitMagazine(unit.unitName, "ASTER 30", 25)
    SM.AddToUnitMagazine(unit.unitName, "114mm N4A1 HE", 648)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 847)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 18486)
    SM.AddToUnitMagazine(unit.unitName, "Sea Skua", 12)
    SM.AddToUnitMagazine(unit.unitName, "Stingray", 24)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "F-15E"
    unit.unitName = "Lancer Flight"
    unit.SetPosition(25.734799, 57.754813, 8000.000000)
    unit.heading = 285.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "GBU-39 SDB", 8)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "AIM-9X", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "GBU-12/B", 4)
    SM.SetUnitLauncherItem(unit.unitName, 4, "GBU-31A(v)2", 2)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Flare-1", 120)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 120)
    SM.SetUnitLauncherItem(unit.unitName, 8, "20mm PGU", 46)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(25.650000, 56.950000, 7600.000000, 390.000000)
    UI.add_waypoint_advanced(26.550000, 56.350000, 7600.000000, 390.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Fort Victoria AOR"
    unit.unitName = "RFA Fort Victoria"
    unit.SetPosition(25.410000, 58.016000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 20.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "20mm Mark 149-4", 118)
    SM.SetUnitLauncherItem(unit.unitName, 1, "20mm Mark 149-4", 118)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.720000)
    SM.AddToUnitMagazine(unit.unitName, "20mm Mark 149-4", 814)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 20.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "E-2C"
    unit.unitName = "Sentinel"
    unit.SetPosition(25.794474, 58.273493, 8000.000000)
    unit.heading = 285.000000
    unit.speed = 324.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.810000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(25.400000, 57.900000, 8500.000000, 260.000000)
    UI.add_waypoint_advanced(25.200000, 58.300000, 8500.000000, 260.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "KC-135R"
    unit.unitName = "Shell 1"
    unit.SetPosition(25.824087, 57.333899, 8000.000000)
    unit.heading = 285.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(25.200000, 58.000000, 9000.000000, 300.000000)
    UI.add_waypoint_advanced(25.000000, 58.500000, 9000.000000, 300.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F/A-18F"
    unit.unitName = "Tiger Flight"
    unit.SetPosition(25.111107, 58.083734, 8000.000000)
    unit.heading = 285.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "1400 liter tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "AIM-120D", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "AIM-120D", 1)
    SM.SetUnitLauncherItem(unit.unitName, 4, "AIM-120D", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "AIM-9X", 1)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm PGU", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 16)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Flare-1", 16)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.700000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(26.050000, 57.300000, 8200.000000, 380.000000)
    UI.add_waypoint_advanced(26.300000, 56.750000, 8200.000000, 380.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Legend WMSL"
    unit.unitName = "USCGC Stone"
    unit.SetPosition(25.440000, 57.952000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 1, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 2, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 3, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 4, "20mm mark 244-0 ELC", 523)
    SM.SetUnitLauncherItem(unit.unitName, 5, "57mm HCER", 840)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.900000)
    SM.AddToUnitMagazine(unit.unitName, ".50 cal bullet", 24000)
    SM.AddToUnitMagazine(unit.unitName, "57mm HCER", 840)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 523)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 34464)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Lewis and Clark"
    unit.unitName = "USNS Amelia Earhart"
    unit.SetPosition(25.470000, 57.888000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 20.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 1000000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 20.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Henry J Kaiser"
    unit.unitName = "USNS John Ericsson"
    unit.SetPosition(25.500000, 57.824000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 20.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 15000000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 20.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 20.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Ticonderoga CG Baseline 4"
    unit.unitName = "USS Chosin"
    unit.SetPosition(25.530000, 57.760000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "SM-2MR Bk3B", 29)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-162A", 64)
    SM.SetUnitLauncherItem(unit.unitName, 2, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 3, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 4, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 6, "127mm mk 80 HE-PD mk 67", 20)
    SM.SetUnitLauncherItem(unit.unitName, 7, "127mm mk 80 HE-PD mk 67", 20)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Mk-54", 3)
    SM.SetUnitLauncherItem(unit.unitName, 9, "Mk-54", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.880000)
    SM.AddToUnitMagazine(unit.unitName, "127mm mk 80 HE-PD mk 67", 1200)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 1046)
    SM.AddToUnitMagazine(unit.unitName, "120 gallon tank", 4)
    SM.AddToUnitMagazine(unit.unitName, "AGM-114 Hellfire", 16)
    SM.AddToUnitMagazine(unit.unitName, "AGM-119B", 4)
    SM.AddToUnitMagazine(unit.unitName, "AGM-65J", 12)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "DICASS (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "DIFAR (110) Sonobuoy", 608)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 49382)
    SM.AddToUnitMagazine(unit.unitName, "LOFAR (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "Mk-50", 2)
    SM.AddToUnitMagazine(unit.unitName, "Mk-54", 34)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Arleigh Burke IIA DDGHM"
    unit.unitName = "USS Mason"
    unit.SetPosition(25.560000, 57.696000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RIM-66M", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-156", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RIM-174A", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "RIM-162B", 11)
    SM.SetUnitLauncherItem(unit.unitName, 4, "RIM-162B", 11)
    SM.SetUnitLauncherItem(unit.unitName, 5, "20mm mark 244-0 ELC", 69)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm mark 244-0 ELC", 69)
    SM.SetUnitLauncherItem(unit.unitName, 7, "RGM-84F Harpoon", 2)
    SM.SetUnitLauncherItem(unit.unitName, 8, "RGM-84F Harpoon", 2)
    SM.SetUnitLauncherItem(unit.unitName, 9, "127mm mk 127 HE-CVT mk 67", 14)
    SM.SetUnitLauncherItem(unit.unitName, 10, "Mk-54", 2)
    SM.SetUnitLauncherItem(unit.unitName, 11, "Mk-54", 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.760000)
    SM.AddToUnitMagazine(unit.unitName, "120 gallon tank", 2)
    SM.AddToUnitMagazine(unit.unitName, "AGM-114 Hellfire", 11)
    SM.AddToUnitMagazine(unit.unitName, "AGM-119B", 2)
    SM.AddToUnitMagazine(unit.unitName, "AGM-65J", 8)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 54)
    SM.AddToUnitMagazine(unit.unitName, "DICASS (110) Sonobuoy", 146)
    SM.AddToUnitMagazine(unit.unitName, "DIFAR (110) Sonobuoy", 437)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 54)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 42648)
    SM.AddToUnitMagazine(unit.unitName, "LOFAR (110) Sonobuoy", 146)
    SM.AddToUnitMagazine(unit.unitName, "Mk-50", 1)
    SM.AddToUnitMagazine(unit.unitName, "Mk-54", 24)
    SM.AddToUnitMagazine(unit.unitName, "BGM-109 TLAM", 25)
    SM.AddToUnitMagazine(unit.unitName, "RIM-156", 7)
    SM.AddToUnitMagazine(unit.unitName, "RIM-174A", 7)
    SM.AddToUnitMagazine(unit.unitName, "RIM-66M", 20)
    SM.AddToUnitMagazine(unit.unitName, "RUM-139 Mod4 ASROC", 8)
    SM.AddToUnitMagazine(unit.unitName, "127mm mk 127 HE-CVT mk 67", 489)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 753)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Cyclone PBFM"
    unit.unitName = "USS Tempest"
    unit.SetPosition(25.590000, 57.632000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, ".50 cal bullet", 468)
    SM.SetUnitLauncherItem(unit.unitName, 1, ".50 cal bullet", 468)
    SM.SetUnitLauncherItem(unit.unitName, 2, ".50 cal bullet", 468)
    SM.SetUnitLauncherItem(unit.unitName, 3, ".50 cal bullet", 468)
    SM.SetUnitLauncherItem(unit.unitName, 4, "25mm APDS", 312)
    SM.SetUnitLauncherItem(unit.unitName, 5, "25mm APDS", 312)
    SM.SetUnitLauncherItem(unit.unitName, 6, "FIM-92 Stinger", 4)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.680000)
    SM.AddToUnitMagazine(unit.unitName, ".50 cal bullet", 5616)
    SM.AddToUnitMagazine(unit.unitName, "25mm APDS", 1872)
    SM.AddToUnitMagazine(unit.unitName, "FIM-92 Stinger", 4)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.380000, 55.760000, 0.000000, 22.000000)

    ##############################
    ### Alliance 2 - RED
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "Airstrip"
    unit.unitName = "Bandar Abbas Strip"
    unit.SetPosition(27.080000, 56.980000, 12.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.840000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 840000)
    SM.AddToUnitMagazine(unit.unitName, "AIM-120C", 77)
    SM.AddToUnitMagazine(unit.unitName, "AIM-9M", 77)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 7700)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 7700)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "K-300P Bastion-P"
    unit.unitName = "Bastion 1"
    unit.SetPosition(26.835440, 56.333700, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "3M10 Granat", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    SM.AddToUnitMagazine(unit.unitName, "3M10 Granat", 3)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)

    unit = SM.GetDefaultUnit()
    unit.className = "K-300P Bastion-P"
    unit.unitName = "Bastion 2"
    unit.SetPosition(26.880000, 56.398544, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "3M10 Granat", 6)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    SM.AddToUnitMagazine(unit.unitName, "3M10 Granat", 6)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)

    unit = SM.GetDefaultUnit()
    unit.className = "Generic Radar Post 170"
    unit.unitName = "Coastwatch 1"
    unit.SetPosition(26.792083, 56.078986, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Generic Mobile Radar Post 170"
    unit.unitName = "Coastwatch 2"
    unit.SetPosition(26.864194, 56.400479, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Kaman FACM"
    unit.unitName = "Falakhon"
    unit.SetPosition(26.420000, 56.380000, 0.000000)
    unit.heading = 135.000000
    unit.speed = 18.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RGM-84A Harpoon", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RGM-84A Harpoon", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "76mm HE-MOM", 22)
    SM.SetUnitLauncherItem(unit.unitName, 3, "40mm HE-T", 14)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.570000)
    SM.AddToUnitMagazine(unit.unitName, "76mm HE-MOM", 67)
    SM.AddToUnitMagazine(unit.unitName, "40mm HE-T", 140)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 18.000000)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 18.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Kaman FACM"
    unit.unitName = "Khanjar"
    unit.SetPosition(26.419000, 56.395000, 0.000000)
    unit.heading = 135.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RGM-84A Harpoon", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RGM-84A Harpoon", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "76mm HE-MOM", 57)
    SM.SetUnitLauncherItem(unit.unitName, 3, "40mm HE-T", 36)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.580000)
    SM.AddToUnitMagazine(unit.unitName, "76mm HE-MOM", 172)
    SM.AddToUnitMagazine(unit.unitName, "40mm HE-T", 360)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.400000, 56.520000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(25.860000, 57.060000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Pantsir-S1"
    unit.unitName = "Pantsir 1"
    unit.SetPosition(26.834632, 56.338093, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Pantsir-S1"
    unit.unitName = "Pantsir 2"
    unit.SetPosition(26.870324, 56.399035, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "S-300PMU-2"
    unit.unitName = "S-300 Site North"
    unit.SetPosition(27.036039, 56.865368, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "48N6E2", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "48N6E2", 4)
    SM.SetUnitLauncherItem(unit.unitName, 2, "48N6E2", 4)
    SM.SetUnitLauncherItem(unit.unitName, 3, "48N6E2", 4)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    SM.AddToUnitMagazine(unit.unitName, "48N6E2", 72)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("PointDefense", 2.000000, 3)

    ##############################
    ### Goals
    ##############################

    goal_temp = SM.ProtectGoal('')
    goal_temp.AddTarget("RFA Fort Victoria")
    goal_temp.AddTarget("USNS Amelia Earhart")
    goal_temp.AddTarget("USNS John Ericsson")
    goal_temp.SetQuantity(2)
    blue_0 = goal_temp
    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("Bastion 1")
    goal_temp.AddTarget("Bastion 2")
    goal_temp.AddTarget("Falakhon")
    goal_temp.AddTarget("Khanjar")
    goal_temp.SetQuantity(2)
    blue_1 = goal_temp
    goal_temp = SM.CompoundGoal(0)
    goal_temp.AddGoal(blue_0)
    goal_temp.AddGoal(blue_1)
    SM.SetAllianceGoal(1, goal_temp)

    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("RFA Fort Victoria")
    goal_temp.AddTarget("USNS Amelia Earhart")
    goal_temp.AddTarget("USNS John Ericsson")
    goal_temp.SetQuantity(2)
    red_goal = goal_temp
    SM.SetAllianceGoal(2, red_goal)

    SM.SetAllianceROEByType(1, 2, 2, 2, 2)
    SM.SetAllianceROEByType(2, 2, 2, 2, 2)
