# Scenario version: 0.2.1
# Generated by Mission Generator v2; RNG seed: crossed-sabers-turn-7-high-action
from math import *


def ScenarioInfo():
    d = dict()
    d['name'] = "Operation Crossed Sabers"
    d['description'] = """Twenty-four hours after Narrow Furnace, the intact convoy completes its westward passage while BLUE launches a coordinated carrier and land-based attack on the remaining coastal kill chain. RED commits both rested Shahin F-14As and every surviving surface raider in a simultaneous counterstroke. The result is a compressed three-axis fight: counter-air over the Strait, surface action around the convoy lanes, and suppression of the Bastion and S-300 belt.

Mission archetype: Limited Strike. This scenario was generated from campaign turn 7 with deterministic seed crossed-sabers-turn-7-high-action."""
    d['author'] = 'Mission Generator v2'
    d['playableSides'] = "Blue"
    d['thumb'] = 'ships3.png'
    d['date'] = "May 2026"
    d['unitCount'] = 45
    d['scenarioId'] = "crossed_sabers_001"
    return d


def CreateScenario(SM):
    SM.SetScenarioInfo(ScenarioInfo())

    SM.CreateAlliance(1, 'Blue')
    SM.AddAllianceCountry(1, 'Blue')
    SM.AddAllianceCountry(1, 'USA')
    SM.AddAllianceCountry(1, 'UK')
    SM.SetAlliancePlayable(1, 1)

    SM.CreateAlliance(2, 'Red')
    SM.AddAllianceCountry(2, 'Red')
    SM.AddAllianceCountry(2, 'Iran')
    SM.SetAlliancePlayable(2, 0)

    SM.SetAllianceRelationship(1, 2, 'Hostile')
    SM.SetUserAlliance(1)
    SM.SetDateTime(2026, 5, 23, 16, 30, 0)
    SM.SetSeaState(3)
    SM.SetSVP("0.000000,1515.000000,200.000000,1500.000000,300.000000,1510.000000,500.000000,1520.000000,5000.000000,1600.000000")

    SM.SetSimpleBriefing(1, """<color=#00a8ff>SITUATION</color>

Twenty-four hours after Narrow Furnace, the intact convoy completes its westward passage while BLUE launches a coordinated carrier and land-based attack on the remaining coastal kill chain. RED commits both rested Shahin F-14As and every surviving surface raider in a simultaneous counterstroke. The result is a compressed three-axis fight: counter-air over the Strait, surface action around the convoy lanes, and suppression of the Bastion and S-300 belt.

<color=#00a8ff>MISSION</color>

Preserve at least 5 of: RFA Fort Victoria, RFA Tidespring, USNS Amelia Earhart, USNS Cesar Chavez, USNS Guadalupe, USNS John Ericsson, USS George H.W. Bush. Also Neutralize at least 2 of: Bastion 1, Bastion 2, Bastion 3. Also Neutralize at least 2 of: Pantsir 1, Pantsir 2, Pantsir 3, S-300 Site North. Also Neutralize at least 4 of: Falakhon, Khanjar, Scimitar, Tsunami 1, Tsunami 2, Zolfaghar.

<color=#00a8ff>EXECUTION</color>

Use Tiger as the flexible carrier element, Viper for precision suppression, and both P-8s for maritime targeting. Protect the carrier and at least four auxiliaries while striking the coastal-missile, air-defense, and surface-raider groups in parallel.

<color=#00a8ff>ROE</color>

BLUE attacks remain limited to forces actively controlling or attacking the Hormuz corridor. Bandar Abbas Strip itself is not a preplanned target, although launched Shahin aircraft may be engaged. Civilian and neutral traffic remains outside the engagement authorization. Neither side is authorized to employ nuclear weapons.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 0.977.""")
    SM.SetSimpleBriefing(2, """<color=#00a8ff>SITUATION</color>

Twenty-four hours after Narrow Furnace, the intact convoy completes its westward passage while BLUE launches a coordinated carrier and land-based attack on the remaining coastal kill chain. RED commits both rested Shahin F-14As and every surviving surface raider in a simultaneous counterstroke. The result is a compressed three-axis fight: counter-air over the Strait, surface action around the convoy lanes, and suppression of the Bastion and S-300 belt.

<color=#00a8ff>MISSION</color>

Neutralize at least 4 of: RFA Fort Victoria, RFA Tidespring, USNS Amelia Earhart, USNS Cesar Chavez, USNS Guadalupe, USNS John Ericsson, USS George H.W. Bush.

<color=#00a8ff>EXECUTION</color>

Launch Shahin immediately to contest the air picture, drive the six surviving raiders into converging attack lanes, and coordinate their pressure with the Bastion and S-300 batteries against BLUE high-value units.

<color=#00a8ff>ROE</color>

BLUE attacks remain limited to forces actively controlling or attacking the Hormuz corridor. Bandar Abbas Strip itself is not a preplanned target, although launched Shahin aircraft may be engaged. Civilian and neutral traffic remains outside the engagement authorization. Neither side is authorized to employ nuclear weapons.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 0.977.""")

    ##############################
    ### Alliance 1 - BLUE
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "Airstrip(USA)"
    unit.unitName = "Al Dhafra Air Base"
    unit.SetPosition(24.248000, 54.547000, 20.000000)
    unit.heading = 285.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    SM.AddToUnitMagazine(unit.unitName, "20mm PGU", 46)
    SM.AddToUnitMagazine(unit.unitName, "AGM-130", 2)
    SM.AddToUnitMagazine(unit.unitName, "AGM-65J", 4)
    SM.AddToUnitMagazine(unit.unitName, "AIM-120D", 2)
    SM.AddToUnitMagazine(unit.unitName, "AIM-9X", 2)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 120)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 120)
    SM.AddToUnitMagazine(unit.unitName, "GBU-12/B", 6)
    SM.AddToUnitMagazine(unit.unitName, "GBU-28B/B", 1)
    SM.AddToUnitMagazine(unit.unitName, "GBU-31A(v)2", 2)
    SM.AddToUnitMagazine(unit.unitName, "GBU-39 SDB", 8)
    SM.AddToUnitMagazine(unit.unitName, "Mk-82", 6)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "P-8 MPA"
    unit.unitName = "Broadarrow"
    unit.SetPosition(26.050000, 57.550000, 7600.000000)
    unit.heading = 300.000000
    unit.speed = 320.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "Mk-46 Mod5", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AGM-84D Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "AN/AAQ-24 Nemesis Laser Beam", 100)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.780000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.200000, 57.100000, 7600.000000, 280.000000)
    UI.add_waypoint_advanced(26.300000, 56.780000, 7600.000000, 280.000000)
    UI.add_waypoint_advanced(25.950000, 57.300000, 7600.000000, 280.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Type 45 DDG"
    unit.unitName = "HMS Diamond"
    unit.SetPosition(26.030000, 57.090000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "ASTER 30", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "ASTER 15", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 3, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 4, "114mm N4A1 HE", 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.760000)
    SM.AddToUnitMagazine(unit.unitName, "ASTER 15", 11)
    SM.AddToUnitMagazine(unit.unitName, "ASTER 30", 31)
    SM.AddToUnitMagazine(unit.unitName, "114mm N4A1 HE", 800)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 1046)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 18012)
    SM.AddToUnitMagazine(unit.unitName, "Sea Skua", 16)
    SM.AddToUnitMagazine(unit.unitName, "Stingray", 30)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.211000, 56.815000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.436000, 56.550000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.466000, 56.400000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.446000, 56.120000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.446000, 55.820000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Type 23 FF"
    unit.unitName = "HMS Richmond"
    unit.SetPosition(25.920000, 57.200000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "Sea Wolf", 6)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 3, "114mm N4A1 HE", 16)
    SM.SetUnitLauncherItem(unit.unitName, 4, "30mm/75 GCM-AO3-2 APDS", 83)
    SM.SetUnitLauncherItem(unit.unitName, 5, "30mm/75 GCM-AO3-2 APDS", 83)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Stingray", 3)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Stingray", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.740000)
    SM.AddToUnitMagazine(unit.unitName, "114mm N4A1 HE", 800)
    SM.AddToUnitMagazine(unit.unitName, "30mm/75 GCM-AO3-2 APDS", 1660)
    SM.AddToUnitMagazine(unit.unitName, "Sea Wolf", 20)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 17538)
    SM.AddToUnitMagazine(unit.unitName, "Sea Skua", 16)
    SM.AddToUnitMagazine(unit.unitName, "Stingray", 29)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.199000, 56.815000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.424000, 56.550000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.454000, 56.400000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.434000, 56.120000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.434000, 55.820000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Fort Victoria AOR"
    unit.unitName = "RFA Fort Victoria"
    unit.SetPosition(25.868000, 57.108000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 12.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "20mm Mark 149-4", 118)
    SM.SetUnitLauncherItem(unit.unitName, 1, "20mm Mark 149-4", 118)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.680000)
    SM.AddToUnitMagazine(unit.unitName, "20mm Mark 149-4", 814)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(26.176000, 56.800000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.401000, 56.535000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.431000, 56.385000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.411000, 56.100000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.411000, 55.800000, 0.000000, 12.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Fort Victoria AOR"
    unit.unitName = "RFA Tidespring"
    unit.SetPosition(25.832000, 57.072000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 12.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "20mm Mark 149-4", 118)
    SM.SetUnitLauncherItem(unit.unitName, 1, "20mm Mark 149-4", 118)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.700000)
    SM.AddToUnitMagazine(unit.unitName, "20mm Mark 149-4", 814)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(26.156000, 56.770000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.391000, 56.525000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.416000, 56.380000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.396000, 56.080000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.396000, 55.780000, 0.000000, 12.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "E-2D"
    unit.unitName = "Sentinel"
    unit.SetPosition(25.350000, 57.900000, 8500.000000)
    unit.heading = 300.000000
    unit.speed = 280.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.800000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(25.450000, 57.650000, 8500.000000, 260.000000)
    UI.add_waypoint_advanced(25.200000, 58.050000, 8500.000000, 260.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "KC-135R"
    unit.unitName = "Shell 1"
    unit.SetPosition(25.100000, 58.100000, 9000.000000)
    unit.heading = 300.000000
    unit.speed = 310.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.920000)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(25.200000, 57.850000, 9000.000000, 300.000000)
    UI.add_waypoint_advanced(24.950000, 58.250000, 9000.000000, 300.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F/A-18F"
    unit.unitName = "Tiger 1"
    unit.SetPosition(25.650000, 57.350000, 8500.000000)
    unit.heading = 300.000000
    unit.speed = 410.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "1400 liter tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "Mk-84", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Mk-84", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Mk-83", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "AIM-9X", 2)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm PGU", 46)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 25)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Flare-1", 25)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F/A-18F"
    unit.unitName = "Tiger 2"
    unit.SetPosition(25.580000, 57.420000, 8500.000000)
    unit.heading = 300.000000
    unit.speed = 410.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "1400 liter tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "Mk-84", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Mk-84", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Mk-83", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "AIM-9X", 2)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm PGU", 46)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 25)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Flare-1", 25)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F/A-18F"
    unit.unitName = "Tiger 3"
    unit.SetPosition(25.620000, 57.820000, 7800.000000)
    unit.heading = 300.000000
    unit.speed = 410.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "1400 liter tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "Mk-84", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Mk-84", 1)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Mk-83", 3)
    SM.SetUnitLauncherItem(unit.unitName, 5, "AIM-9X", 1)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm PGU", 35)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 19)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Flare-1", 19)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.820000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.950000, 57.300000, 8200.000000, 380.000000)
    UI.add_waypoint_advanced(26.280000, 56.820000, 8200.000000, 380.000000)
    UI.add_waypoint_advanced(26.020000, 57.380000, 8200.000000, 380.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F/A-18F"
    unit.unitName = "Tiger 4"
    unit.SetPosition(25.580000, 57.880000, 7800.000000)
    unit.heading = 300.000000
    unit.speed = 410.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "1400 liter tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "Mk-84", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Mk-84", 1)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Mk-83", 3)
    SM.SetUnitLauncherItem(unit.unitName, 5, "AIM-9X", 1)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm PGU", 35)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 19)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Flare-1", 19)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.820000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.910000, 57.340000, 8200.000000, 380.000000)
    UI.add_waypoint_advanced(26.240000, 56.880000, 8200.000000, 380.000000)
    UI.add_waypoint_advanced(25.980000, 57.420000, 8200.000000, 380.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "P-8 MPA"
    unit.unitName = "Trident"
    unit.SetPosition(25.550000, 58.100000, 7600.000000)
    unit.heading = 300.000000
    unit.speed = 320.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "Mk-46 Mod5", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AGM-84D Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "AN/AAQ-24 Nemesis Laser Beam", 100)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.760000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(25.750000, 57.750000, 7600.000000, 280.000000)
    UI.add_waypoint_advanced(25.450000, 58.200000, 7600.000000, 280.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Legend WMSL"
    unit.unitName = "USCGC Stone"
    unit.SetPosition(25.900000, 57.000000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 14.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 1, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 2, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 3, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 4, "20mm mark 244-0 ELC", 523)
    SM.SetUnitLauncherItem(unit.unitName, 5, "57mm HCER", 840)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.680000)
    SM.AddToUnitMagazine(unit.unitName, ".50 cal bullet", 24000)
    SM.AddToUnitMagazine(unit.unitName, "57mm HCER", 840)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 523)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 26039)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.152000, 56.770000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.387000, 56.525000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.412000, 56.380000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.392000, 56.080000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.392000, 55.780000, 0.000000, 14.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Lewis and Clark"
    unit.unitName = "USNS Amelia Earhart"
    unit.SetPosition(25.958000, 57.018000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 12.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.880000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 880000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(26.184000, 56.800000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.409000, 56.535000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.439000, 56.385000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.419000, 56.100000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.419000, 55.800000, 0.000000, 12.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Lewis and Clark"
    unit.unitName = "USNS Cesar Chavez"
    unit.SetPosition(25.922000, 56.982000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 12.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.860000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 860000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(26.164000, 56.770000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.399000, 56.525000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.424000, 56.380000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.404000, 56.080000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.404000, 55.780000, 0.000000, 12.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Henry J Kaiser"
    unit.unitName = "USNS Guadalupe"
    unit.SetPosition(25.877000, 57.027000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 12.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.840000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 12600000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(26.160000, 56.770000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.395000, 56.525000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.420000, 56.380000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.400000, 56.080000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.400000, 55.780000, 0.000000, 12.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Henry J Kaiser"
    unit.unitName = "USNS John Ericsson"
    unit.SetPosition(25.913000, 57.063000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 12.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.860000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 12900000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(26.180000, 56.800000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.405000, 56.535000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.435000, 56.385000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.415000, 56.100000, 0.000000, 12.000000)
    UI.add_waypoint_advanced(26.415000, 55.800000, 0.000000, 12.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Arleigh Burke III DDGHM"
    unit.unitName = "USS Arleigh Burke"
    unit.SetPosition(25.785000, 57.045000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RIM-174A", 24)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-162B", 64)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RIM-156", 32)
    SM.SetUnitLauncherItem(unit.unitName, 3, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 4, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 5, "RGM-84G Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 6, "RGM-84G Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 7, "127mm mk 127 HE-CVT mk 67", 20)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Mk-54", 3)
    SM.SetUnitLauncherItem(unit.unitName, 9, "Mk-54", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.740000)
    SM.AddToUnitMagazine(unit.unitName, "120 gallon tank", 4)
    SM.AddToUnitMagazine(unit.unitName, "AGM-114 Hellfire", 16)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "DICASS (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "DIFAR (110) Sonobuoy", 608)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 41526)
    SM.AddToUnitMagazine(unit.unitName, "LOFAR (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "Mk-54", 34)
    SM.AddToUnitMagazine(unit.unitName, "BGM-109 TLAM", 36)
    SM.AddToUnitMagazine(unit.unitName, "RIM-174A", 20)
    SM.AddToUnitMagazine(unit.unitName, "RUM-139 Mod4 ASROC", 12)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 1046)
    SM.AddToUnitMagazine(unit.unitName, "127mm mk 127 HE-CVT mk 67", 680)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.134000, 56.770000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.384000, 56.530000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.414000, 56.380000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.394000, 56.080000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.394000, 55.780000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Ticonderoga CG Baseline 4"
    unit.unitName = "USS Chosin"
    unit.SetPosition(25.975000, 57.145000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "SM-2MR Bk3B", 29)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-162A", 64)
    SM.SetUnitLauncherItem(unit.unitName, 2, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 3, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 4, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 6, "127mm mk 80 HE-PD mk 67", 20)
    SM.SetUnitLauncherItem(unit.unitName, 7, "127mm mk 80 HE-PD mk 67", 20)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Mk-54", 3)
    SM.SetUnitLauncherItem(unit.unitName, 9, "Mk-54", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.750000)
    SM.AddToUnitMagazine(unit.unitName, "127mm mk 80 HE-PD mk 67", 1200)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 1046)
    SM.AddToUnitMagazine(unit.unitName, "120 gallon tank", 4)
    SM.AddToUnitMagazine(unit.unitName, "AGM-114 Hellfire", 16)
    SM.AddToUnitMagazine(unit.unitName, "AGM-119B", 4)
    SM.AddToUnitMagazine(unit.unitName, "AGM-65J", 12)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "DICASS (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "DIFAR (110) Sonobuoy", 608)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 42087)
    SM.AddToUnitMagazine(unit.unitName, "LOFAR (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "Mk-50", 2)
    SM.AddToUnitMagazine(unit.unitName, "Mk-54", 34)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.205000, 56.815000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.430000, 56.550000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.460000, 56.400000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.440000, 56.120000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.440000, 55.820000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Avenger MCM"
    unit.unitName = "USS Devastator"
    unit.SetPosition(25.980000, 56.925000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 10.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 1, ".50 cal bullet", 600)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.650000)
    SM.AddToUnitMagazine(unit.unitName, ".50 cal bullet", 12000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.168000, 56.770000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.403000, 56.525000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.428000, 56.380000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.408000, 56.080000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.408000, 55.780000, 0.000000, 10.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Avenger MCM"
    unit.unitName = "USS Dextrous"
    unit.SetPosition(26.015000, 56.955000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 10.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 1, ".50 cal bullet", 600)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.650000)
    SM.AddToUnitMagazine(unit.unitName, ".50 cal bullet", 12000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.188000, 56.800000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.413000, 56.535000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.443000, 56.385000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.423000, 56.100000, 0.000000, 10.000000)
    UI.add_waypoint_advanced(26.423000, 55.800000, 0.000000, 10.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "CVN-77 (Nimitz) USS George H.W. Bush"
    unit.unitName = "USS George H.W. Bush"
    unit.SetPosition(25.323411, 58.113014, 0.000000)
    unit.heading = 305.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.820000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(25.400000, 57.950000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(25.550000, 57.750000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(25.350000, 58.050000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Arleigh Burke IIA DDGHM"
    unit.unitName = "USS Mason"
    unit.SetPosition(25.895000, 56.935000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RIM-66M", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-156", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RIM-174A", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "RIM-162B", 15)
    SM.SetUnitLauncherItem(unit.unitName, 4, "RIM-162B", 15)
    SM.SetUnitLauncherItem(unit.unitName, 5, "20mm mark 244-0 ELC", 95)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm mark 244-0 ELC", 95)
    SM.SetUnitLauncherItem(unit.unitName, 7, "RGM-84F Harpoon", 3)
    SM.SetUnitLauncherItem(unit.unitName, 8, "RGM-84F Harpoon", 3)
    SM.SetUnitLauncherItem(unit.unitName, 9, "127mm mk 127 HE-CVT mk 67", 19)
    SM.SetUnitLauncherItem(unit.unitName, 10, "Mk-54", 2)
    SM.SetUnitLauncherItem(unit.unitName, 11, "Mk-54", 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.670000)
    SM.AddToUnitMagazine(unit.unitName, "120 gallon tank", 3)
    SM.AddToUnitMagazine(unit.unitName, "AGM-114 Hellfire", 15)
    SM.AddToUnitMagazine(unit.unitName, "AGM-119B", 3)
    SM.AddToUnitMagazine(unit.unitName, "AGM-65J", 11)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 73)
    SM.AddToUnitMagazine(unit.unitName, "DICASS (110) Sonobuoy", 198)
    SM.AddToUnitMagazine(unit.unitName, "DIFAR (110) Sonobuoy", 595)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 73)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 37598)
    SM.AddToUnitMagazine(unit.unitName, "LOFAR (110) Sonobuoy", 198)
    SM.AddToUnitMagazine(unit.unitName, "Mk-50", 1)
    SM.AddToUnitMagazine(unit.unitName, "Mk-54", 33)
    SM.AddToUnitMagazine(unit.unitName, "BGM-109 TLAM", 35)
    SM.AddToUnitMagazine(unit.unitName, "RIM-156", 9)
    SM.AddToUnitMagazine(unit.unitName, "RIM-174A", 9)
    SM.AddToUnitMagazine(unit.unitName, "RIM-66M", 27)
    SM.AddToUnitMagazine(unit.unitName, "RUM-139 Mod4 ASROC", 11)
    SM.AddToUnitMagazine(unit.unitName, "127mm mk 127 HE-CVT mk 67", 666)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 1025)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.146000, 56.770000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.396000, 56.530000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.426000, 56.380000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.406000, 56.080000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.406000, 55.780000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Cyclone PBFM"
    unit.unitName = "USS Tempest"
    unit.SetPosition(25.945000, 57.075000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 14.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 1, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 2, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 3, ".50 cal bullet", 600)
    SM.SetUnitLauncherItem(unit.unitName, 4, "25mm APDS", 400)
    SM.SetUnitLauncherItem(unit.unitName, 5, "25mm APDS", 400)
    SM.SetUnitLauncherItem(unit.unitName, 6, "FIM-92 Stinger", 6)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.610000)
    SM.AddToUnitMagazine(unit.unitName, ".50 cal bullet", 7200)
    SM.AddToUnitMagazine(unit.unitName, "25mm APDS", 2400)
    SM.AddToUnitMagazine(unit.unitName, "FIM-92 Stinger", 6)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.172000, 56.800000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.397000, 56.535000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.427000, 56.385000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.407000, 56.100000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(26.407000, 55.800000, 0.000000, 14.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Arleigh Burke IIA DDGHM"
    unit.unitName = "USS Thomas Hudner"
    unit.SetPosition(25.840000, 56.990000, 0.000000)
    unit.heading = 285.000000
    unit.speed = 16.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RIM-66M", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-156", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RIM-174A", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "RIM-162B", 16)
    SM.SetUnitLauncherItem(unit.unitName, 4, "RIM-162B", 16)
    SM.SetUnitLauncherItem(unit.unitName, 5, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm mark 244-0 ELC", 97)
    SM.SetUnitLauncherItem(unit.unitName, 7, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 8, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 9, "127mm mk 127 HE-CVT mk 67", 20)
    SM.SetUnitLauncherItem(unit.unitName, 10, "Mk-54", 3)
    SM.SetUnitLauncherItem(unit.unitName, 11, "Mk-54", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.730000)
    SM.AddToUnitMagazine(unit.unitName, "120 gallon tank", 4)
    SM.AddToUnitMagazine(unit.unitName, "AGM-114 Hellfire", 16)
    SM.AddToUnitMagazine(unit.unitName, "AGM-119B", 4)
    SM.AddToUnitMagazine(unit.unitName, "AGM-65J", 12)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "DICASS (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "DIFAR (110) Sonobuoy", 608)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 75)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 40965)
    SM.AddToUnitMagazine(unit.unitName, "LOFAR (110) Sonobuoy", 203)
    SM.AddToUnitMagazine(unit.unitName, "Mk-50", 2)
    SM.AddToUnitMagazine(unit.unitName, "Mk-54", 34)
    SM.AddToUnitMagazine(unit.unitName, "BGM-109 TLAM", 36)
    SM.AddToUnitMagazine(unit.unitName, "RIM-156", 10)
    SM.AddToUnitMagazine(unit.unitName, "RIM-174A", 10)
    SM.AddToUnitMagazine(unit.unitName, "RIM-66M", 28)
    SM.AddToUnitMagazine(unit.unitName, "RUM-139 Mod4 ASROC", 12)
    SM.AddToUnitMagazine(unit.unitName, "127mm mk 127 HE-CVT mk 67", 680)
    SM.AddToUnitMagazine(unit.unitName, "20mm mark 244-0 ELC", 1046)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.140000, 56.769000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.390000, 56.529000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.420000, 56.379000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.400000, 56.079000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(26.400000, 55.779000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "F-15E"
    unit.unitName = "Viper 1"
    unit.SetPosition(25.250000, 56.550000, 7600.000000)
    unit.heading = 300.000000
    unit.speed = 410.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "AGM-130", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "AIM-9X", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "GBU-12/B", 4)
    SM.SetUnitLauncherItem(unit.unitName, 4, "GBU-31A(v)2", 2)
    SM.SetUnitLauncherItem(unit.unitName, 5, "GBU-28B/B", 1)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Flare-1", 120)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 120)
    SM.SetUnitLauncherItem(unit.unitName, 8, "20mm PGU", 46)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F-15E"
    unit.unitName = "Viper 2"
    unit.SetPosition(25.180000, 56.620000, 7600.000000)
    unit.heading = 300.000000
    unit.speed = 410.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "AGM-130", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "AIM-9X", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "GBU-12/B", 4)
    SM.SetUnitLauncherItem(unit.unitName, 4, "GBU-31A(v)2", 2)
    SM.SetUnitLauncherItem(unit.unitName, 5, "GBU-28B/B", 1)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Flare-1", 120)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Chaff-1", 120)
    SM.SetUnitLauncherItem(unit.unitName, 8, "20mm PGU", 46)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.SetNavLoopState(True)

    # MAINTENANCE: Wildcat 1
    SM.AddUnitToFlightDeck("Al Dhafra Air Base", "F-15E", "Wildcat 1", 1)
    SM.SetFlightDeckUnitLoadout("Al Dhafra Air Base", "Wildcat 1", "46 20mm PGU;2 AGM-130;2 AIM-120D;2 AIM-9X;120 Chaff-1;120 Flare-1;4 GBU-12/B;1 GBU-28B/B;2 GBU-31A(v)2;")

    ##############################
    ### Alliance 2 - RED
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "Airstrip"
    unit.unitName = "Bandar Abbas Strip"
    unit.SetPosition(27.080000, 56.980000, 12.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.900000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 900000)
    SM.AddToUnitMagazine(unit.unitName, "AIM-120C", 85)
    SM.AddToUnitMagazine(unit.unitName, "AIM-9M", 85)
    SM.AddToUnitMagazine(unit.unitName, "Chaff-1", 8500)
    SM.AddToUnitMagazine(unit.unitName, "Flare-1", 8500)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "K-300P Bastion-P"
    unit.unitName = "Bastion 1"
    unit.SetPosition(26.835440, 56.333700, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "P-800 Oniks", 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)

    unit = SM.GetDefaultUnit()
    unit.className = "K-300P Bastion-P"
    unit.unitName = "Bastion 2"
    unit.SetPosition(26.880000, 56.398544, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "P-800 Oniks", 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)

    unit = SM.GetDefaultUnit()
    unit.className = "K-300P Bastion-P"
    unit.unitName = "Bastion 3"
    unit.SetPosition(27.052409, 56.483620, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "P-800 Oniks", 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)

    unit = SM.GetDefaultUnit()
    unit.className = "Kaman FACM"
    unit.unitName = "Falakhon"
    unit.SetPosition(26.400000, 56.460000, 0.000000)
    unit.heading = 110.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "40mm HE-T", 12)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.500000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.350000, 56.570000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.210000, 56.700000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.070000, 56.820000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Kaman FACM"
    unit.unitName = "Khanjar"
    unit.SetPosition(26.430000, 56.440000, 0.000000)
    unit.heading = 110.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RGM-84A Harpoon", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "76mm HE-MOM", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "40mm HE-T", 20)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.520000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.380000, 56.550000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.240000, 56.680000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.100000, 56.800000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Pantsir-S1"
    unit.unitName = "Pantsir 1"
    unit.SetPosition(26.834632, 56.338093, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Pantsir-S1"
    unit.unitName = "Pantsir 2"
    unit.SetPosition(26.870324, 56.399035, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Pantsir-S1"
    unit.unitName = "Pantsir 3"
    unit.SetPosition(27.053302, 56.482007, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "S-300PMU-2"
    unit.unitName = "S-300 Site North"
    unit.SetPosition(27.036039, 56.865368, 10.000000)
    unit.heading = 135.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitAlwaysVisibleState(unit.unitName, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "48N6E2", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "48N6E2", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "48N6E2", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "48N6E2", 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("PointDefense", 2.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Kaman FACM"
    unit.unitName = "Scimitar"
    unit.SetPosition(26.370000, 55.700000, 0.000000)
    unit.heading = 110.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RGM-84A Harpoon", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RGM-84A Harpoon", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "76mm HE-MOM", 80)
    SM.SetUnitLauncherItem(unit.unitName, 3, "40mm HE-T", 50)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.720000)
    SM.AddToUnitMagazine(unit.unitName, "76mm HE-MOM", 240)
    SM.AddToUnitMagazine(unit.unitName, "40mm HE-T", 500)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.370000, 55.980000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.370000, 56.160000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.360000, 56.300000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "F-14A"
    unit.unitName = "Shahin 1"
    unit.SetPosition(26.680000, 56.750000, 9200.000000)
    unit.heading = 190.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "20mm PGU", 46)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-54C ECCM", 4)
    SM.SetUnitLauncherItem(unit.unitName, 2, "AIM-9M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "AIM-7M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.350000, 56.450000, 9200.000000, 420.000000)
    UI.add_waypoint_advanced(25.950000, 56.750000, 8800.000000, 420.000000)
    UI.add_waypoint_advanced(26.450000, 56.950000, 9200.000000, 420.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F-14A"
    unit.unitName = "Shahin 2"
    unit.SetPosition(26.620000, 56.840000, 9200.000000)
    unit.heading = 190.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "20mm PGU", 46)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-54C ECCM", 4)
    SM.SetUnitLauncherItem(unit.unitName, 2, "AIM-9M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "AIM-7M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(1.000000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("AirEvade", 3.000000, 3)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.280000, 56.520000, 9000.000000, 420.000000)
    UI.add_waypoint_advanced(25.880000, 56.820000, 8600.000000, 420.000000)
    UI.add_waypoint_advanced(26.380000, 57.020000, 9000.000000, 420.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Pr 205ER Tsunami (Iran)"
    unit.unitName = "Tsunami 1"
    unit.SetPosition(26.270000, 55.620000, 0.000000)
    unit.heading = 110.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "P-21 Termit", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "30mm OF-83 HE-FRAG", 250)
    SM.SetUnitLauncherItem(unit.unitName, 2, "30mm OF-83 HE-FRAG", 250)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.700000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.270000, 55.900000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.270000, 56.040000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.280000, 56.120000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Pr 205ER Tsunami (Iran)"
    unit.unitName = "Tsunami 2"
    unit.SetPosition(26.220000, 55.580000, 0.000000)
    unit.heading = 110.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "P-21 Termit", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "30mm OF-83 HE-FRAG", 250)
    SM.SetUnitLauncherItem(unit.unitName, 2, "30mm OF-83 HE-FRAG", 250)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.700000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.220000, 55.860000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.220000, 55.980000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.240000, 56.060000, 0.000000, 22.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Kaman FACM"
    unit.unitName = "Zolfaghar"
    unit.SetPosition(26.320000, 55.660000, 0.000000)
    unit.heading = 110.000000
    unit.speed = 22.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RGM-84A Harpoon", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RGM-84A Harpoon", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "76mm HE-MOM", 80)
    SM.SetUnitLauncherItem(unit.unitName, 3, "40mm HE-T", 50)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.720000)
    SM.AddToUnitMagazine(unit.unitName, "76mm HE-MOM", 240)
    SM.AddToUnitMagazine(unit.unitName, "40mm HE-T", 500)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(26.320000, 55.940000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.320000, 56.120000, 0.000000, 22.000000)
    UI.add_waypoint_advanced(26.310000, 56.260000, 0.000000, 22.000000)

    ##############################
    ### Goals
    ##############################

    goal_temp = SM.ProtectGoal('')
    goal_temp.AddTarget("RFA Fort Victoria")
    goal_temp.AddTarget("RFA Tidespring")
    goal_temp.AddTarget("USNS Amelia Earhart")
    goal_temp.AddTarget("USNS Cesar Chavez")
    goal_temp.AddTarget("USNS Guadalupe")
    goal_temp.AddTarget("USNS John Ericsson")
    goal_temp.AddTarget("USS George H.W. Bush")
    goal_temp.SetQuantity(5)
    blue_0 = goal_temp
    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("Bastion 1")
    goal_temp.AddTarget("Bastion 2")
    goal_temp.AddTarget("Bastion 3")
    goal_temp.SetQuantity(2)
    blue_1 = goal_temp
    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("Pantsir 1")
    goal_temp.AddTarget("Pantsir 2")
    goal_temp.AddTarget("Pantsir 3")
    goal_temp.AddTarget("S-300 Site North")
    goal_temp.SetQuantity(2)
    blue_2 = goal_temp
    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("Falakhon")
    goal_temp.AddTarget("Khanjar")
    goal_temp.AddTarget("Scimitar")
    goal_temp.AddTarget("Tsunami 1")
    goal_temp.AddTarget("Tsunami 2")
    goal_temp.AddTarget("Zolfaghar")
    goal_temp.SetQuantity(4)
    blue_3 = goal_temp
    goal_temp = SM.CompoundGoal(0)
    goal_temp.AddGoal(blue_0)
    goal_temp.AddGoal(blue_1)
    goal_temp.AddGoal(blue_2)
    goal_temp.AddGoal(blue_3)
    SM.SetAllianceGoal(1, goal_temp)

    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("RFA Fort Victoria")
    goal_temp.AddTarget("RFA Tidespring")
    goal_temp.AddTarget("USNS Amelia Earhart")
    goal_temp.AddTarget("USNS Cesar Chavez")
    goal_temp.AddTarget("USNS Guadalupe")
    goal_temp.AddTarget("USNS John Ericsson")
    goal_temp.AddTarget("USS George H.W. Bush")
    goal_temp.SetQuantity(4)
    red_goal = goal_temp
    SM.SetAllianceGoal(2, red_goal)

    SM.SetAllianceROEByType(1, 2, 2, 2, 2)
    SM.SetAllianceROEByType(2, 2, 2, 2, 2)
