# Scenario version: 0.2.1
# Generated by Mission Generator v2; RNG seed: baltic-shield-turn-1
from math import *


def ScenarioInfo():
    d = dict()
    d['name'] = "Operation Baltic Shield - First Contact"
    d['description'] = """FICTIONAL ALTERNATE TIMELINE, June 2026. Ten days of crisis allowed precautionary deployments. A maritime confrontation escalated into reciprocal weapons fire overnight. NATO must preserve a supply ship and forward air operations against a limited Russian air-maritime attack off Latvia. No land invasion has begun. This is a bounded game force package, not a claim about actual deployments.

Mission archetype: Convoy Escort. This scenario was generated from campaign turn 1 with deterministic seed baltic-shield-turn-1."""
    d['author'] = 'Mission Generator v2'
    d['playableSides'] = "NATO"
    d['thumb'] = 'ships3.png'
    d['date'] = "June 2026"
    d['unitCount'] = 36
    d['scenarioId'] = "baltic_shield_001"
    return d


def CreateScenario(SM):
    SM.SetScenarioInfo(ScenarioInfo())

    SM.CreateAlliance(1, "NATO")
    SM.AddAllianceCountry(1, "Germany")
    SM.AddAllianceCountry(1, "UK")
    SM.AddAllianceCountry(1, "USA")
    SM.AddAllianceCountry(1, "Latvia")
    SM.AddAllianceCountry(1, "Estonia")
    SM.SetAlliancePlayable(1, 1)

    SM.CreateAlliance(2, "Russia")
    SM.AddAllianceCountry(2, "Russia")
    SM.SetAlliancePlayable(2, 0)

    SM.SetAllianceRelationship(1, 2, 'Hostile')
    SM.SetUserAlliance(1)
    SM.SetDateTime(2026, 6, 15, 7, 30, 0)
    SM.SetSeaState(3)
    SM.SetSVP("0.000000,1480.000000,20.000000,1475.000000,60.000000,1460.000000,150.000000,1470.000000,500.000000,1490.000000")

    SM.SetSimpleBriefing(1, """<color=#00a8ff>SITUATION</color>

FICTIONAL ALTERNATE TIMELINE, June 2026. Ten days of crisis allowed precautionary deployments. A maritime confrontation escalated into reciprocal weapons fire overnight. NATO must preserve a supply ship and forward air operations against a limited Russian air-maritime attack off Latvia. No land invasion has begun. This is a bounded game force package, not a claim about actual deployments.

<color=#00a8ff>MISSION</color>

Preserve at least 3 of: Amari Air Base, Baltic Sustainment 1, Lielvarde Air Base. Also Neutralize at least 2 of: Fencer Maritime 1, Fencer Maritime 2, Fencer Strike 1, Fencer Strike 2. Also Neutralize at least 1 of: Russian Corvette 1, Russian Corvette 2.

<color=#00a8ff>EXECUTION</color>

Preserve Baltic Sustainment 1 and both forward air bases. Defeat two strike aircraft and one forward corvette. Combine CAP, ship defenses and shore SAM cover. SEAD and precision-strike aircraft begin on hold for player tasking; attack only designated coastal threats when needed.

<color=#00a8ff>ROE</color>

Conventional weapons only. NATO shore engagement is restricted by commander intent to Russian Coastal Battery, Russian Coastal Radar, Russian SAM Sector and Russian Point Defense. Briefing guidance is not an engine-enforced whitelist. Russian Air Base and civilian infrastructure are not NATO victory targets. Ground maneuver formations and occupation of Latvia or Estonia are outside this opening air-maritime battle.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 0.875.""")
    SM.SetSimpleBriefing(2, """<color=#00a8ff>SITUATION</color>

FICTIONAL ALTERNATE TIMELINE, June 2026. Ten days of crisis allowed precautionary deployments. A maritime confrontation escalated into reciprocal weapons fire overnight. NATO must preserve a supply ship and forward air operations against a limited Russian air-maritime attack off Latvia. No land invasion has begun. This is a bounded game force package, not a claim about actual deployments.

<color=#00a8ff>MISSION</color>

Neutralize at least 1 of: Amari Air Base, Baltic Sustainment 1, Lielvarde Air Base.

<color=#00a8ff>EXECUTION</color>

Disrupt NATO sustainment and forward air operations with two maritime-strike and two land-strike aircraft, fighter cover and two forward corvettes. A frigate supports the naval force; coastal defenses protect the southern approaches.

<color=#00a8ff>ROE</color>

Conventional weapons only. NATO shore engagement is restricted by commander intent to Russian Coastal Battery, Russian Coastal Radar, Russian SAM Sector and Russian Point Defense. Briefing guidance is not an engine-enforced whitelist. Russian Air Base and civilian infrastructure are not NATO victory targets. Ground maneuver formations and occupation of Latvia or Estonia are outside this opening air-maritime battle.

<color=#00a8ff>ASSESSMENT</color>

Generated difficulty ratio: 0.875.""")

    ##############################
    ### Alliance 1 - BLUE
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "Airbase"
    unit.unitName = "Amari Air Base"
    unit.SetPosition(59.260000, 24.210000, 10.000000)
    unit.heading = 0.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Henry J Kaiser"
    unit.unitName = "Baltic Sustainment 1"
    unit.SetPosition(56.150000, 20.120000, 0.000000)
    unit.heading = 0.000000
    unit.speed = 18.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 14250000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.675000, 20.120000, 0.000000, 14.000000)
    UI.add_waypoint_advanced(57.200000, 20.120000, 0.000000, 14.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Generic Radar Post 170"
    unit.unitName = "Estonia Radar Post"
    unit.SetPosition(59.180000, 24.250000, 10.000000)
    unit.heading = 0.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "MIM-104 Patriot PAC-2"
    unit.unitName = "Estonia SAM Detachment"
    unit.SetPosition(59.220000, 24.300000, 10.000000)
    unit.heading = 0.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "MIM-104C", 8)
    SM.SetUnitLauncherItem(unit.unitName, 1, "MIM-104C", 8)
    SM.SetUnitLauncherItem(unit.unitName, 2, "MIM-104C", 8)
    SM.SetUnitLauncherItem(unit.unitName, 3, "MIM-104C", 8)
    SM.SetUnitLauncherItem(unit.unitName, 4, "MIM-104D", 8)
    SM.SetUnitLauncherItem(unit.unitName, 5, "MIM-104D", 8)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    SM.AddToUnitMagazine(unit.unitName, "MIM-104C", 32)
    SM.AddToUnitMagazine(unit.unitName, "MIM-104D", 16)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("PointDefense", 2.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "F-16C/D Block 50"
    unit.unitName = "Falcon Precision Strike 1"
    unit.SetPosition(56.890000, 24.000000, 6500.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "AIM-9X", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "GBU-12/B", 6)
    SM.SetUnitLauncherItem(unit.unitName, 3, "370 gallon wing tank", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "300 gallon wing tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Flare-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "20mm PGU", 46)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(56.850000, 23.800000, 6500.000000, 380.000000)
    UI.add_waypoint_advanced(57.100000, 24.200000, 6500.000000, 380.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "F-16C/D Block 50"
    unit.unitName = "Falcon Precision Strike 2"
    unit.SetPosition(56.930000, 24.000000, 6500.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "AIM-9X", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120D", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "GBU-12/B", 6)
    SM.SetUnitLauncherItem(unit.unitName, 3, "370 gallon wing tank", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "300 gallon wing tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Flare-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "20mm PGU", 46)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(56.850000, 23.800000, 6500.000000, 380.000000)
    UI.add_waypoint_advanced(57.100000, 24.200000, 6500.000000, 380.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Generic Mobile Radar Post 170"
    unit.unitName = "Latvia Radar Post"
    unit.SetPosition(56.900000, 24.800000, 10.000000)
    unit.heading = 0.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "MIM-104 Patriot PAC-3"
    unit.unitName = "Latvia SAM Detachment"
    unit.SetPosition(56.800000, 24.900000, 10.000000)
    unit.heading = 0.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "ERINT/PAC-3", 32)
    SM.SetUnitLauncherItem(unit.unitName, 1, "MIM-104C", 8)
    SM.SetUnitLauncherItem(unit.unitName, 2, "MIM-104C", 8)
    SM.SetUnitLauncherItem(unit.unitName, 3, "MIM-104C", 8)
    SM.SetUnitLauncherItem(unit.unitName, 4, "MIM-104D", 8)
    SM.SetUnitLauncherItem(unit.unitName, 5, "MIM-104D", 8)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    SM.AddToUnitMagazine(unit.unitName, "ERINT/PAC-3", 32)
    SM.AddToUnitMagazine(unit.unitName, "MIM-104C", 24)
    SM.AddToUnitMagazine(unit.unitName, "MIM-104D", 16)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("PointDefense", 2.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Airbase"
    unit.unitName = "Lielvarde Air Base"
    unit.SetPosition(56.780000, 24.850000, 10.000000)
    unit.heading = 0.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "E-3C"
    unit.unitName = "Magic AEW"
    unit.SetPosition(57.300000, 23.800000, 9500.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(57.100000, 23.600000, 9500.000000, 300.000000)
    UI.add_waypoint_advanced(57.500000, 24.000000, 9500.000000, 300.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Sachsen FFGHM"
    unit.unitName = "NATO Air Defense Frigate"
    unit.SetPosition(56.250000, 20.250000, 0.000000)
    unit.heading = 0.000000
    unit.speed = 18.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RIM-66M", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-162B", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RIM-116B RAM", 21)
    SM.SetUnitLauncherItem(unit.unitName, 3, "RIM-116B RAM", 21)
    SM.SetUnitLauncherItem(unit.unitName, 4, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 5, "RGM-84F Harpoon", 4)
    SM.SetUnitLauncherItem(unit.unitName, 6, "76mm HE-MOM", 80)
    SM.SetUnitLauncherItem(unit.unitName, 7, "27mm DM10 FAPDS", 90)
    SM.SetUnitLauncherItem(unit.unitName, 8, "27mm DM10 FAPDS", 90)
    SM.SetUnitLauncherItem(unit.unitName, 9, "MU-90", 3)
    SM.SetUnitLauncherItem(unit.unitName, 10, "MU-90", 3)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 22515)
    SM.AddToUnitMagazine(unit.unitName, "Mk-46 Mod5", 29)
    SM.AddToUnitMagazine(unit.unitName, "Sea Skua", 16)
    SM.AddToUnitMagazine(unit.unitName, "RIM-162B", 32)
    SM.AddToUnitMagazine(unit.unitName, "RIM-66M", 24)
    SM.AddToUnitMagazine(unit.unitName, "RIM-116B RAM", 84)
    SM.AddToUnitMagazine(unit.unitName, "76mm HE-MOM", 240)
    SM.AddToUnitMagazine(unit.unitName, "27mm DM10 FAPDS", 1000)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(56.775000, 20.250000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(57.300000, 20.250000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Brandenburg FFGHM"
    unit.unitName = "NATO ASW Frigate"
    unit.SetPosition(56.300000, 20.050000, 0.000000)
    unit.heading = 0.000000
    unit.speed = 18.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "RIM-7P(v2)", 1)
    SM.SetUnitLauncherItem(unit.unitName, 1, "RIM-116B RAM", 21)
    SM.SetUnitLauncherItem(unit.unitName, 2, "RIM-116B RAM", 21)
    SM.SetUnitLauncherItem(unit.unitName, 3, "MM-40 B3 Exocet", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "MM-40 B3 Exocet", 2)
    SM.SetUnitLauncherItem(unit.unitName, 5, "76mm HE-MOM", 80)
    SM.SetUnitLauncherItem(unit.unitName, 6, "20mm Rh202 HE-T", 50)
    SM.SetUnitLauncherItem(unit.unitName, 7, "20mm Rh202 HE-T", 50)
    SM.SetUnitLauncherItem(unit.unitName, 8, "Mk-46 Mod5", 2)
    SM.SetUnitLauncherItem(unit.unitName, 9, "Mk-46 Mod5", 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 22515)
    SM.AddToUnitMagazine(unit.unitName, "Mk-46 Mod5", 29)
    SM.AddToUnitMagazine(unit.unitName, "Sea Skua", 16)
    SM.AddToUnitMagazine(unit.unitName, "76mm HE-MOM", 240)
    SM.AddToUnitMagazine(unit.unitName, "RIM-116B RAM", 42)
    SM.AddToUnitMagazine(unit.unitName, "20mm Rh202 HE-T", 1000)
    SM.AddToUnitMagazine(unit.unitName, "RIM-7P(v2)", 15)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(56.825000, 20.050000, 0.000000, 16.000000)
    UI.add_waypoint_advanced(57.350000, 20.050000, 0.000000, 16.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Tornado ECR (Germany)"
    unit.unitName = "Raven SEAD Strike 1"
    unit.SetPosition(56.590000, 23.400000, 6500.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "Chaff-1", 50)
    SM.SetUnitLauncherItem(unit.unitName, 1, "Flare-1", 50)
    SM.SetUnitLauncherItem(unit.unitName, 2, "IRIS-T", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "IRIS-T", 1)
    SM.SetUnitLauncherItem(unit.unitName, 4, "330 gallon wing tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "330 gallon wing tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 6, "AGM-88B", 1)
    SM.SetUnitLauncherItem(unit.unitName, 7, "AGM-88B", 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(56.600000, 23.300000, 6500.000000, 360.000000)
    UI.add_waypoint_advanced(56.900000, 23.600000, 6500.000000, 360.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Tornado ECR (Germany)"
    unit.unitName = "Raven SEAD Strike 2"
    unit.SetPosition(56.630000, 23.400000, 6500.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "Chaff-1", 50)
    SM.SetUnitLauncherItem(unit.unitName, 1, "Flare-1", 50)
    SM.SetUnitLauncherItem(unit.unitName, 2, "IRIS-T", 1)
    SM.SetUnitLauncherItem(unit.unitName, 3, "IRIS-T", 1)
    SM.SetUnitLauncherItem(unit.unitName, 4, "330 gallon wing tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "330 gallon wing tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 6, "AGM-88B", 1)
    SM.SetUnitLauncherItem(unit.unitName, 7, "AGM-88B", 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(56.600000, 23.300000, 6500.000000, 360.000000)
    UI.add_waypoint_advanced(56.900000, 23.600000, 6500.000000, 360.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "P-8 MPA"
    unit.unitName = "Seeker MPA"
    unit.SetPosition(57.100000, 21.500000, 5000.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "Mk-46 Mod5", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AGM-84D Harpoon", 2)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(56.900000, 21.300000, 5000.000000, 300.000000)
    UI.add_waypoint_advanced(57.300000, 21.700000, 5000.000000, 300.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "KC-135R"
    unit.unitName = "Shell Tanker"
    unit.SetPosition(57.800000, 24.000000, 8500.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("Nav", 2.000000, 3)
    UI.add_waypoint_advanced(57.600000, 23.800000, 8500.000000, 300.000000)
    UI.add_waypoint_advanced(58.000000, 24.200000, 8500.000000, 300.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Typhoon"
    unit.unitName = "Viper CAP 1"
    unit.SetPosition(56.580000, 20.900000, 8000.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "ASRAAM", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120C7", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "AIM-120C7", 4)
    SM.SetUnitLauncherItem(unit.unitName, 4, "1150 Liter Tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "27mm BK27 27x145mm", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.700000, 20.700000, 8000.000000, 420.000000)
    UI.add_waypoint_advanced(57.200000, 21.200000, 8000.000000, 420.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Typhoon"
    unit.unitName = "Viper CAP 2"
    unit.SetPosition(56.610000, 20.900000, 8000.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "ASRAAM", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120C7", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "AIM-120C7", 4)
    SM.SetUnitLauncherItem(unit.unitName, 4, "1150 Liter Tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "27mm BK27 27x145mm", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.700000, 20.700000, 8000.000000, 420.000000)
    UI.add_waypoint_advanced(57.200000, 21.200000, 8000.000000, 420.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Typhoon"
    unit.unitName = "Viper CAP 3"
    unit.SetPosition(58.490000, 23.900000, 8000.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "ASRAAM", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120C7", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "AIM-120C7", 4)
    SM.SetUnitLauncherItem(unit.unitName, 4, "1150 Liter Tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "27mm BK27 27x145mm", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(58.600000, 24.000000, 8000.000000, 420.000000)
    UI.add_waypoint_advanced(59.200000, 24.400000, 8000.000000, 420.000000)
    UI.SetNavLoopState(True)

    unit = SM.GetDefaultUnit()
    unit.className = "Typhoon"
    unit.unitName = "Viper CAP 4"
    unit.SetPosition(58.520000, 23.900000, 8000.000000)
    unit.heading = 0.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 1)
    SM.SetUnitLauncherItem(unit.unitName, 0, "ASRAAM", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "AIM-120C7", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "AIM-120C7", 4)
    SM.SetUnitLauncherItem(unit.unitName, 4, "1150 Liter Tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 5, "27mm BK27 27x145mm", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(58.600000, 24.000000, 8000.000000, 420.000000)
    UI.add_waypoint_advanced(59.200000, 24.400000, 8000.000000, 420.000000)
    UI.SetNavLoopState(True)

    ##############################
    ### Alliance 2 - RED
    ##############################

    unit = SM.GetDefaultUnit()
    unit.className = "Su-24M"
    unit.unitName = "Fencer Maritime 1"
    unit.SetPosition(55.790000, 21.300000, 1500.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-60", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "Kh-59MK", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "23mm AM-23", 6)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.250000, 20.800000, 1500.000000, 420.000000)
    UI.add_waypoint_advanced(56.500000, 20.500000, 1500.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Su-24M"
    unit.unitName = "Fencer Maritime 2"
    unit.SetPosition(55.830000, 21.300000, 1500.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-60", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "Kh-59MK", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "23mm AM-23", 6)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.250000, 20.800000, 1500.000000, 420.000000)
    UI.add_waypoint_advanced(56.500000, 20.500000, 1500.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Su-24M"
    unit.unitName = "Fencer Strike 1"
    unit.SetPosition(55.990000, 23.200000, 1800.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-60", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "3000 liter tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "Kh-29T", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "KAB-500L", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "23mm AM-23", 6)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.500000, 24.100000, 1800.000000, 420.000000)
    UI.add_waypoint_advanced(56.720000, 24.700000, 1800.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Su-24M"
    unit.unitName = "Fencer Strike 2"
    unit.SetPosition(56.030000, 23.200000, 1800.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-60", 2)
    SM.SetUnitLauncherItem(unit.unitName, 1, "3000 liter tank", 1)
    SM.SetUnitLauncherItem(unit.unitName, 2, "Kh-29T", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "KAB-500L", 2)
    SM.SetUnitLauncherItem(unit.unitName, 4, "23mm AM-23", 6)
    SM.SetUnitLauncherItem(unit.unitName, 5, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 6, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.500000, 24.100000, 1800.000000, 420.000000)
    UI.add_waypoint_advanced(56.720000, 24.700000, 1800.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Su-27"
    unit.unitName = "Flanker CAP 1"
    unit.SetPosition(55.590000, 21.700000, 8500.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-27R", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "R-73M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "R-27R", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.000000, 21.300000, 8500.000000, 420.000000)
    UI.add_waypoint_advanced(56.600000, 21.500000, 8500.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Su-27"
    unit.unitName = "Flanker CAP 2"
    unit.SetPosition(55.630000, 21.600000, 8500.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-27R", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "R-73M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "R-27R", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.000000, 21.300000, 8500.000000, 420.000000)
    UI.add_waypoint_advanced(56.600000, 21.500000, 8500.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Su-27"
    unit.unitName = "Flanker CAP 3"
    unit.SetPosition(55.670000, 21.700000, 8500.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-27R", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "R-73M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "R-27R", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.000000, 21.300000, 8500.000000, 420.000000)
    UI.add_waypoint_advanced(56.600000, 21.500000, 8500.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Su-27"
    unit.unitName = "Flanker CAP 4"
    unit.SetPosition(55.710000, 21.600000, 8500.000000)
    unit.heading = 315.000000
    unit.speed = 420.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "R-27R", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "R-73M", 2)
    SM.SetUnitLauncherItem(unit.unitName, 2, "R-27R", 2)
    SM.SetUnitLauncherItem(unit.unitName, 3, "Chaff-1", 30)
    SM.SetUnitLauncherItem(unit.unitName, 4, "Flare-1", 30)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.850000)
    UI.SetAllSensorState(1)
    UI.AddTask("Aircraft1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)
    UI.AddTask("Nav", 3.000000, 3)
    UI.add_waypoint_advanced(56.000000, 21.300000, 8500.000000, 420.000000)
    UI.add_waypoint_advanced(56.600000, 21.500000, 8500.000000, 420.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Airstrip (Russia)"
    unit.unitName = "Russian Air Base"
    unit.SetPosition(54.770000, 20.400000, 10.000000)
    unit.heading = 315.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "K-300P Bastion-P"
    unit.unitName = "Russian Coastal Battery"
    unit.SetPosition(54.900000, 20.350000, 10.000000)
    unit.heading = 315.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "P-800 Oniks", 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("AutoAttack", 2.000000, 0)

    unit = SM.GetDefaultUnit()
    unit.className = "Generic Radar Post 170"
    unit.unitName = "Russian Coastal Radar"
    unit.SetPosition(54.900000, 20.200000, 10.000000)
    unit.heading = 315.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Pr 20380 Steregushchiy"
    unit.unitName = "Russian Corvette 1"
    unit.SetPosition(56.800000, 20.400000, 0.000000)
    unit.heading = 315.000000
    unit.speed = 18.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "100mm OF-58 FRAG", 46)
    SM.SetUnitLauncherItem(unit.unitName, 1, "12.7mm B-32 APi", 17)
    SM.SetUnitLauncherItem(unit.unitName, 2, "12.7mm B-32 APi", 17)
    SM.SetUnitLauncherItem(unit.unitName, 3, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 4, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 5, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 6, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Kh-35", 8)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    SM.AddToUnitMagazine(unit.unitName, "100mm OF-58 FRAG", 350)
    SM.AddToUnitMagazine(unit.unitName, "12.7mm B-32 APi", 680)
    SM.AddToUnitMagazine(unit.unitName, "30mm OF-84 HE-FRAG AK-630M", 472)
    SM.AddToUnitMagazine(unit.unitName, "9M311 Kashtan", 48)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(56.500000, 20.400000, 0.000000, 18.000000)
    UI.add_waypoint_advanced(56.200000, 20.400000, 0.000000, 18.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Pr 20380 Steregushchiy"
    unit.unitName = "Russian Corvette 2"
    unit.SetPosition(57.100000, 20.500000, 0.000000)
    unit.heading = 315.000000
    unit.speed = 18.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "100mm OF-58 FRAG", 46)
    SM.SetUnitLauncherItem(unit.unitName, 1, "12.7mm B-32 APi", 17)
    SM.SetUnitLauncherItem(unit.unitName, 2, "12.7mm B-32 APi", 17)
    SM.SetUnitLauncherItem(unit.unitName, 3, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 4, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 5, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 6, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 7, "Kh-35", 8)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    SM.AddToUnitMagazine(unit.unitName, "100mm OF-58 FRAG", 350)
    SM.AddToUnitMagazine(unit.unitName, "12.7mm B-32 APi", 680)
    SM.AddToUnitMagazine(unit.unitName, "30mm OF-84 HE-FRAG AK-630M", 472)
    SM.AddToUnitMagazine(unit.unitName, "9M311 Kashtan", 48)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(56.725000, 20.500000, 0.000000, 18.000000)
    UI.add_waypoint_advanced(56.350000, 20.500000, 0.000000, 18.000000)

    unit = SM.GetDefaultUnit()
    unit.className = "Pantsir-S1"
    unit.unitName = "Russian Point Defense"
    unit.SetPosition(54.900000, 20.700000, 10.000000)
    unit.heading = 315.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    UI.AddTask("Ground1", 1.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "S-300PMU-2"
    unit.unitName = "Russian SAM Sector"
    unit.SetPosition(54.850000, 20.800000, 10.000000)
    unit.heading = 315.000000
    unit.speed = 0.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "48N6E2", 4)
    SM.SetUnitLauncherItem(unit.unitName, 1, "48N6E2", 4)
    SM.SetUnitLauncherItem(unit.unitName, 2, "48N6E2", 4)
    SM.SetUnitLauncherItem(unit.unitName, 3, "48N6E2", 4)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    UI.SetAllSensorState(1)
    SM.AddToUnitMagazine(unit.unitName, "48N6E2", 72)
    UI.AddTask("Ground1", 1.000000, 3)
    UI.AddTask("PointDefense", 2.000000, 3)

    unit = SM.GetDefaultUnit()
    unit.className = "Pr 11540 Yastreb"
    unit.unitName = "Russian Support Frigate"
    unit.SetPosition(55.650000, 20.300000, 0.000000)
    unit.heading = 315.000000
    unit.speed = 18.000000
    unit.cost = 0.0
    SM.AddUnitToAlliance(unit, 2)
    SM.SetUnitLauncherItem(unit.unitName, 0, "100mm OF-58 FRAG", 46)
    SM.SetUnitLauncherItem(unit.unitName, 1, "53-65M", 3)
    SM.SetUnitLauncherItem(unit.unitName, 2, "53-65M", 3)
    SM.SetUnitLauncherItem(unit.unitName, 3, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 4, "30mm OF-84 HE-FRAG AK-630M", 59)
    SM.SetUnitLauncherItem(unit.unitName, 5, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 6, "9M311 Kashtan", 8)
    SM.SetUnitLauncherItem(unit.unitName, 7, "9M330 Kinzhal", 32)
    UI = SM.GetUnitInterface(unit.unitName)
    UI.SetFuelFraction(0.950000)
    SM.AddToUnitMagazine(unit.unitName, "100mm OF-58 FRAG", 350)
    SM.AddToUnitMagazine(unit.unitName, "53-65M", 12)
    SM.AddToUnitMagazine(unit.unitName, "9M311 Kashtan", 48)
    SM.AddToUnitMagazine(unit.unitName, "30mm OF-84 HE-FRAG AK-630M", 472)
    SM.AddToUnitMagazine(unit.unitName, "AT-1", 18)
    SM.AddToUnitMagazine(unit.unitName, "DICASS (105) Sonobuoy", 105)
    SM.AddToUnitMagazine(unit.unitName, "DIFAR (105) Sonobuoy", 294)
    SM.AddToUnitMagazine(unit.unitName, "Fuel", 21802)
    SM.AddToUnitMagazine(unit.unitName, "LOFAR (105) Sonobuoy", 105)
    UI.AddTask("Ship1", 1.000000, 3)
    UI.AddTask("ShipDefense", 2.000000, 3)
    UI.AddTask("AutoAttack", 3.000000, 0)
    UI.AddTask("Nav", 4.000000, 3)
    UI.add_waypoint_advanced(55.975000, 20.300000, 0.000000, 18.000000)
    UI.add_waypoint_advanced(56.300000, 20.300000, 0.000000, 18.000000)

    ##############################
    ### Goals
    ##############################

    goal_temp = SM.ProtectGoal('')
    goal_temp.AddTarget("Amari Air Base")
    goal_temp.AddTarget("Baltic Sustainment 1")
    goal_temp.AddTarget("Lielvarde Air Base")
    goal_temp.SetQuantity(3)
    blue_0 = goal_temp
    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("Fencer Maritime 1")
    goal_temp.AddTarget("Fencer Maritime 2")
    goal_temp.AddTarget("Fencer Strike 1")
    goal_temp.AddTarget("Fencer Strike 2")
    goal_temp.SetQuantity(2)
    blue_1 = goal_temp
    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("Russian Corvette 1")
    goal_temp.AddTarget("Russian Corvette 2")
    goal_temp.SetQuantity(1)
    blue_2 = goal_temp
    goal_temp = SM.CompoundGoal(0)
    goal_temp.AddGoal(blue_0)
    goal_temp.AddGoal(blue_1)
    goal_temp.AddGoal(blue_2)
    SM.SetAllianceGoal(1, goal_temp)

    goal_temp = SM.DestroyGoal('')
    goal_temp.AddTarget("Amari Air Base")
    goal_temp.AddTarget("Baltic Sustainment 1")
    goal_temp.AddTarget("Lielvarde Air Base")
    goal_temp.SetQuantity(1)
    red_goal = goal_temp
    SM.SetAllianceGoal(2, red_goal)

    SM.SetAllianceROEByType(1, 2, 2, 2, 2)
    SM.SetAllianceROEByType(2, 2, 2, 2, 2)
